### PR TITLE
Sync submodule cmake

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jcarpent** [comment]
@nim65s do you know what happens in ROS TSID CI?

**Comment by jcarpent** [comment]
I will merge this PR as the issue on ROS is not related to this PR.

**Comment by wxmerkt** [comment]
For some reason it cannot find hppfcl on the Python path after installing the Rolling binaries. Which is curious since this used to work. Will need to investigate

**Comment by nim65s** [comment]
I tried an ubuntu 22.04 wis ROS rolling.

`dpkg -L ros-rolling-hpp-fcl` shows `/opt/ros/rolling/lib/python3/dist-packages/hppfcl/__init__.py`
`source /opt/ros/rolling/setup.bash && python3 -c "import sys;print(sys.path)"` shows `/opt/ros/rolling/lib/python3.10/site-packages`.

So I think the rolling package for hpp-fcl is missing a `-DPYTHON_STANDARD_LAYOUT=ON` and/or a `-DPYTHON_DEB_LAYOUT=OFF`

**Comment by wxmerkt** [comment]
Thank you for verifying @nim65s. My hunch is that this is due to the difference between ROS1 packaging (where we use debian layout) and ROS2 packaging (where we use standard layout). 
I am surprised to see the issue though since we explicitly take care of the pythonpath by
https://github.com/humanoid-path-planner/hpp-fcl/blob/3bc5c8d371c742815efe414a99ad0251a60e8e60/CMakeLists.txt#L288

I.e. I wonder if PYTHON_SITELIB is not matching where we install?

**Comment by wxmerkt** [comment]
Ok, I found the issue. There was a new track cut for rolling by @cottsay two weeks ago which somehow dropped our patch that is available in Galactic, Rolling, etc. to activate the PYTHON_STANDARD_LAYOUT

Correct patches on humble: https://github.com/ros2-gbp/hpp_fcl-release/tree/patches/release/humble/hpp-fcl
No patches on rolling: https://github.com/ros2-gbp/hpp_fcl-release/tree/patches/release/rolling/hpp-fcl

Since this will likely also affect our other repositories, @cottsay is there a reason why patches got dropped and do we have to manually re-add them?

**Comment by cottsay** [comment]
> Since this will likely also affect our other repositories, is there a reason why patches got dropped and do we have to manually re-add them?

The underlying cause was ros/rosdistro#32128. We hit the same bug when we migrated Rolling to Jammy. Unfortunately, it's difficult to determine what packages were affected, but I tried to clean up all of the issues I encountered during the rebuild. Clearly I missed this one.

I've restored the patches. Here's the release: ros/rosdistro#36698

Sorry for the inconvenience and confusion - we're working on possible solutions for this bug.

**Comment by wxmerkt** [comment]
Thank you for the detail and fix @cottsay. We'll ping if we discover other repositories that dropped their patches :-)

**Comment by jcarpent** [comment]
Thanks @cottsay for the insight. Very helpful.
And thanks a lot for your efforts, that's very precious.

**Pull request merged**
