### PR TITLE
cmake required >= 3.19 to create interface library with source files

### PR DESCRIPTION
**Pull request by fabinsch**
solves #8 

see doc https://cmake.org/cmake/help/latest/command/add_library.html#interface-libraries

### CODE REVIEW

**Review by jcarpent — CHANGES_REQUESTED** [review]
It would be nicer to keep a minimal version compatible with Ubuntu 18.04 and to adjust the code accordingly?

**Comment by fabinsch** [comment]
hey @jcarpent , to me it seemed from this page here that cmake 3.19 can be installed with Ubuntu 18.04 (https://robots.uc3m.es/installation-guides/install-cmake.html#install-cmake-319-ubuntu-1804-bionic). Anyway, I will adapt it to use the `include_target_directory` like this we do not need to change the minimal cmake version..

**Comment by jcarpent** [comment]
> hey @jcarpent , to me it seemed from this page here that cmake 3.19 can be installed with Ubuntu 18.04 (https://robots.uc3m.es/installation-guides/install-cmake.html#install-cmake-319-ubuntu-1804-bionic). Anyway, I will adapt it to use the `include_target_directory` like this we do not need to change the minimal cmake version..

But this is not the default version provided by Ubuntu. We should comply with this rule.

**Comment by jcarpent** [comment]
pre-commit.ci autofix

**Comment by jcarpent** [comment]
Redundant with #17.

**Pull request closed without merging**
