### PR TITLE
Fixed temporaries in update() of dense wrapper

### PR DESCRIPTION
**Pull request by fennel-labs**
The update() method dense wrapper differs in its function signature from setup(), such that Eigen::Ref<Eigen::Vector> objects cannot be passed as vectors. Instead plain Eigen::Vector objects are passed. This has the negative side effect of creating temporaries.

### CODE REVIEW

**Comment by fennel-labs** [comment]
@jcarpent CLA assitant does not work as it provides no option to select.

**Review by jcarpent — APPROVED** [review]

**Comment by fennel-labs** [comment]
I am wondering, whether all `optional<MatRef<T>>(dense::MatRef<T>(model.A))`-like conversions are necessary. Shouldn't the compiler figure out that it needs to convert to std::optional? 
(the setup method in all examples is also called without this pattern)

**Comment by jcarpent** [comment]
> @jcarpent CLA assitant does not work as it provides no option to select.

@fennel-labs Thanks for this useful contribution.
You need to link your commit address to your GitHub account as mentioned in [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by jcarpent** [comment]
@fennel-labs I will complement your PR with minor changes ...

**Comment by jcarpent** [comment]
I will fix the compilation issues too. Is it fine?

**Comment by jcarpent** [comment]
> I am wondering, whether all `optional<MatRef<T>>(dense::MatRef<T>(model.A))`-like conversions are necessary. Shouldn't the compiler figure out that it needs to convert to std::optional? (the setup method in all examples is also called without this pattern)

Yes, you're right.

**Review by jcarpent — APPROVED** [review]

**Review by jcarpent — APPROVED** [review]

**Comment by jcarpent** [comment]
Great work @fennel-labs. Thanks a lot for fixing useless allocation.

**Pull request merged**
