### PR TITLE
[CI] ROS: Activate prerelease

### PR DESCRIPTION
**Pull request by wxmerkt**
To check if we could move to packaging/vendoring

### CODE REVIEW

**Comment by jcarpent** [comment]
@wxmerkt It seems that `CMAKE_ARGS` is not parsed by the CI. Do you know why?

**Comment by wxmerkt** [comment]
I believe it's because this is a PRERELEASE build that would require a different kind of patching (in a release repo). The idea was to check with this if we are ready to package/distribute via the ROS buildfarm as requested in #178 but I got very busy so didn't have more time to investigate or add a solution - one way to do this is to quickly address it is to check if simde is available in QUIET/CONFIG mode, warn if vectorisation is on and simde not found, and then turn vectorisation off. Would this be workable? This would avoid patching but still keep users informed that if they want vectorisation they need to provide the package.

Alternatively, we can think about (a) vendoring simde to 20.04/noetic or (b) falling back to an ExternalProject/FetchContent since it's header-only [but then would need to install it which isn't ideal]

If you are interested in packaging/distributing via the ROS buildfarm, please let me know and I could look into this more closely next week - alternatively also happy to close the PR for now and come back to it later

**Comment by wep21** [comment]
@wxmerkt @jcarpent Is it possible to release to `ros2-gbp` first? I guess it is ready for ros2 release.

**Comment by jcarpent** [comment]
@wxmerkt @wep21 What are the next steps? Should we enable ccache?

**Comment by wxmerkt** [comment]
I turned off ccache since it appears to cause the issues with prerelease we've been seeing with ci@master.

As for next steps, if you are happy we'd merge this branch and then can request a ros2-gbp release repository. If you'd like to distribute via the ROS buildfarm I'm happy to help out. The plan would be rolling first (to test), then humble. For ROS1/noetic, we need to first vendor simde. Please let me know what your thoughts / plans are

@wep21: Do you have an application/package in mind that would use proxsuite so we can enable downstream tests / verify the binaries once they are released?

A good first test would be to try tsid with proxsuite on ROS2. Perhaps @olivier-stasse already looked into something like this (or has other ROS2 use cases in mind) that we could use to validate the packages?

**Comment by jcarpent** [comment]
> As for next steps, if you are happy we'd merge this branch and then can request a ros2-gbp release repository.

Do you need a new release for that?

**Comment by wxmerkt** [comment]
@jcarpent Yes please :-)

**Comment by jcarpent** [comment]
@wxmerkt The release is out. Thanks a lot for you efforts @wxmerkt @wep21

**Pull request merged**
