### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by wxmerkt** [comment]
Good morning @jcarpent, I can see the new tag for the release 0.3.7 but the main branch is still on the older release. Is this correct/intended?

**Comment by jcarpent** [comment]
> Good morning @jcarpent, I can see the new tag for the release 0.3.7 but the main branch is still on the older release. Is this correct/intended?

Pushing on the main branch requires to have the test passing well. This is not the case at this time. We will enforce it.

**Comment by jcarpent** [comment]
@wxmerkt Do you know what happens with the ROS ci?

**Comment by wxmerkt** [comment]
The failure on ROS Humble Pre-release is a time-out for one of the tests:
```
  125/145 Test #125: dense maros meszaros using the api ..................................................................................................................................................................***Timeout 1500.01 sec
```

Is this already using Release mode by default? Have you seen it reach the timeout before / would it need to be increased?

**Comment by jcarpent** [comment]
Thanks @wxmerkt for your help.

**Pull request closed without merging**
