### PR TITLE
Expose check_duality_gap in Python settings

### PR DESCRIPTION
**Pull request by stephane-caron**

### CODE REVIEW

**Review by jcarpent — APPROVED** [review]

**Comment by stephane-caron** [comment]
Describe the duality gap check and the rationale for it in the documentation.

PR is still in draft state. Feedback is welcome at any stage, the draft flag is just here to let you know that there are more commits coming :wink: I will switch it out of draft when I feel ``check_duality_gap`` has been fully wired/documented.

**Comment by stephane-caron** [comment]
Ready for review! Apart from code correctness, please check that the additional doc on ``check_duality_gap`` is accurate and reflects the motivation behind this new parameter.

**Review by jcarpent — APPROVED** [review]
Looks good to me.
@stephane-caronThanks a lot for providing further insights and for completely supporting the activation of the duality gap check.
@Bambade Could you provide a review of this PR?

**Comment by Bambade** [comment]
Thanks a lot @stephane-caron ! I have just modified a bit the documentation. Looks good for me otherwise.

**Review by jcarpent — APPROVED** [review]

**Pull request merged**
